/* Generated by scripts/bundle-function.mjs. Edit server/wod-levels.ts. */
//#region src/metconSim.ts
var CARDIO = [
	{
		id: "run",
		label: "Correr"
	},
	{
		id: "bikerg",
		label: "BikeErg"
	},
	{
		id: "skierg",
		label: "SkiErg"
	},
	{
		id: "rowerg",
		label: "RowErg"
	},
	{
		id: "assault",
		label: "Assault bike"
	}
];
var EXERCISES = [
	{
		id: "deadlift",
		name: "Peso muerto",
		group: "barra",
		pacing: {
			min: 1.8,
			max: 2.5
		},
		sprint: {
			min: 1.2,
			max: 1.5
		}
	},
	{
		id: "squat",
		name: "Front squat / Back squat",
		group: "barra",
		pacing: {
			min: 2,
			max: 2.5
		},
		sprint: {
			min: 1.5,
			max: 1.5
		}
	},
	{
		id: "thruster",
		name: "Thruster",
		group: "barra",
		pacing: {
			min: 2.5,
			max: 3
		},
		sprint: {
			min: 2,
			max: 2
		}
	},
	{
		id: "clean",
		name: "Power clean / Hang clean",
		group: "barra",
		pacing: {
			min: 2,
			max: 2.8
		},
		sprint: {
			min: 1.5,
			max: 1.8
		}
	},
	{
		id: "snatch",
		name: "Snatch",
		group: "barra",
		pacing: {
			min: 2.5,
			max: 3.5
		},
		sprint: {
			min: 1.8,
			max: 2.2
		}
	},
	{
		id: "jerk",
		name: "Push press / Push jerk",
		group: "barra",
		pacing: {
			min: 1.5,
			max: 2
		},
		sprint: {
			min: 1,
			max: 1.2
		}
	},
	{
		id: "devil-press",
		name: "Dumbbell devil press",
		group: "barra",
		pacing: {
			min: 4.5,
			max: 6
		},
		sprint: {
			min: 3.5,
			max: 4
		}
	},
	{
		id: "db-snatch",
		name: "Dumbbell snatch (alterno)",
		group: "barra",
		pacing: {
			min: 2.5,
			max: 3
		},
		sprint: {
			min: 1.8,
			max: 2.2
		}
	},
	{
		id: "pullup-kipping",
		name: "Pull-ups kipping",
		group: "gimnasticos",
		pacing: {
			min: 1.2,
			max: 1.5
		},
		sprint: {
			min: .8,
			max: 1
		}
	},
	{
		id: "pullup-butterfly",
		name: "Pull-ups butterfly",
		group: "gimnasticos",
		pacing: {
			min: .8,
			max: 1
		},
		sprint: {
			min: .6,
			max: .7
		}
	},
	{
		id: "toes-to-bar",
		name: "Toes to bar",
		group: "gimnasticos",
		pacing: {
			min: 1.5,
			max: 1.8
		},
		sprint: {
			min: 1.1,
			max: 1.3
		}
	},
	{
		id: "chest-to-bar",
		name: "Chest to bar",
		group: "gimnasticos",
		pacing: {
			min: 1.5,
			max: 2
		},
		sprint: {
			min: 1.1,
			max: 1.3
		}
	},
	{
		id: "muscle-up",
		name: "Bar / Ring muscle-up",
		group: "gimnasticos",
		pacing: {
			min: 3,
			max: 4
		},
		sprint: {
			min: 2.2,
			max: 2.5
		}
	},
	{
		id: "hspu",
		name: "HSPU kipping",
		group: "gimnasticos",
		pacing: {
			min: 1.8,
			max: 2.3
		},
		sprint: {
			min: 1.2,
			max: 1.5
		}
	},
	{
		id: "pushup",
		name: "Push-ups",
		group: "gimnasticos",
		pacing: {
			min: 1.2,
			max: 1.5
		},
		sprint: {
			min: .8,
			max: 1
		}
	},
	{
		id: "air-squat",
		name: "Air squats",
		group: "gimnasticos",
		pacing: {
			min: 1,
			max: 1.3
		},
		sprint: {
			min: .7,
			max: .8
		}
	},
	{
		id: "burpee",
		name: "Burpees",
		group: "otros",
		pacing: {
			min: 3,
			max: 4
		},
		sprint: {
			min: 2,
			max: 2.5
		}
	},
	{
		id: "burpee-bar",
		name: "Burpees over the bar",
		group: "otros",
		pacing: {
			min: 3.5,
			max: 4.5
		},
		sprint: {
			min: 2.5,
			max: 3
		}
	},
	{
		id: "wall-ball",
		name: "Wall balls",
		group: "otros",
		pacing: {
			min: 2.2,
			max: 2.6
		},
		sprint: {
			min: 1.8,
			max: 2
		}
	},
	{
		id: "lunge",
		name: "Zancadas",
		group: "otros",
		pacing: {
			min: 1.5,
			max: 1.8
		},
		sprint: {
			min: 1,
			max: 1.2
		},
		meterPacing: {
			min: 1.5,
			max: 1.8
		},
		meterSprint: {
			min: 1,
			max: 1.2
		},
		units: ["reps", "meters"],
		unitNote: "En repeticiones, cada una es una pierna. En metros, el tiempo es por metro."
	},
	{
		id: "farmer-carry",
		name: "Farmer carry",
		group: "otros",
		pacing: {
			min: 1.2,
			max: 1.8
		},
		sprint: {
			min: .7,
			max: 1
		},
		meterPacing: {
			min: 1.2,
			max: 1.8
		},
		meterSprint: {
			min: .7,
			max: 1
		},
		units: ["meters"],
		unitNote: "El tiempo es por metro. El peso es por mano."
	},
	{
		id: "box-jump",
		name: "Box jumps",
		group: "otros",
		pacing: {
			min: 2.5,
			max: 3.5
		},
		sprint: {
			min: 1.8,
			max: 2
		},
		unitNote: "El sprint cuenta el rebote."
	},
	{
		id: "kettlebell",
		name: "Kettlebell swings",
		group: "otros",
		pacing: {
			min: 2,
			max: 2.5
		},
		sprint: {
			min: 1.6,
			max: 1.8
		}
	},
	{
		id: "double-under",
		name: "Double unders",
		group: "otros",
		pacing: {
			min: .6,
			max: .7
		},
		sprint: {
			min: .4,
			max: .5
		}
	},
	{
		id: "rope",
		name: "Subida a la cuerda (4,5 m)",
		group: "otros",
		pacing: {
			min: 10,
			max: 15
		},
		sprint: {
			min: 6,
			max: 8
		},
		unitNote: "Cada repetición es una subida."
	}
];
function exerciseUnits(def) {
	return def.units ?? ["reps"];
}
function workRange(def, mode, unit) {
	if (unit === "meters") {
		const meters = mode === "sprint" ? def.meterSprint : def.meterPacing;
		if (meters) return meters;
	}
	return mode === "sprint" ? def.sprint : def.pacing;
}
//#endregion
//#region src/wodScore.ts
function repsPerRound(reps) {
	if (reps.length === 0) return null;
	let total = 0;
	for (const value of reps) {
		if (!/^\d+$/.test(value.trim())) return null;
		const parsed = Number(value);
		if (!Number.isInteger(parsed) || parsed <= 0) return null;
		total += parsed;
	}
	return total;
}
function compareValue(type, score, perRound) {
	if (type === "for_time") return score.elapsedSec ?? Number.POSITIVE_INFINITY;
	if (type === "amrap") {
		const rounds = score.rounds ?? 0;
		const extra = score.reps ?? 0;
		if (perRound != null) return rounds * perRound + extra;
		return rounds * 1e6 + extra;
	}
	return score.reps ?? 0;
}
function formatScoreLabel(type, score) {
	if (type === "for_time") return formatClock(score.elapsedSec ?? 0);
	if (type === "amrap") {
		const rounds = score.rounds ?? 0;
		const extra = score.reps ?? 0;
		if (rounds === 0) return extra === 1 ? "1 rep" : `${extra} reps`;
		const roundLabel = rounds === 1 ? "1 ronda" : `${rounds} rondas`;
		if (extra === 0) return roundLabel;
		return `${roundLabel} + ${extra}`;
	}
	const reps = score.reps ?? 0;
	return reps === 1 ? "1 rep" : `${reps} reps`;
}
function formatClock(totalSeconds) {
	const total = Math.max(0, Math.round(totalSeconds));
	return `${Math.floor(total / 60)}:${(total % 60).toString().padStart(2, "0")}`;
}
//#endregion
//#region src/wodLevels.ts
var LEVELS = [
	{
		id: "scaled",
		label: "Escalado"
	},
	{
		id: "intermediate",
		label: "Intermedio"
	},
	{
		id: "rx",
		label: "RX"
	}
];
var TRANSITION = {
	scaled: 8,
	intermediate: 4,
	rx: 2
};
var BETWEEN = {
	scaled: 15,
	intermediate: 8,
	rx: 4
};
var FATIGUE = {
	scaled: 1.12,
	intermediate: 1.06,
	rx: 1.03
};
var GENERIC_SEC = {
	scaled: 4,
	intermediate: 3,
	rx: 2.2
};
var REFERENCE_KG = {
	deadlift: 100,
	squat: 60,
	thruster: 43,
	clean: 60,
	snatch: 43,
	jerk: 43,
	"devil-press": 22.5,
	"db-snatch": 22.5,
	"wall-ball": 9,
	kettlebell: 24,
	"farmer-carry": 24
};
var DISTANCE_PACE = {
	run: {
		scaled: 390,
		intermediate: 300,
		rx: 240
	},
	rowerg: {
		scaled: 300,
		intermediate: 252,
		rx: 216
	},
	skierg: {
		scaled: 312,
		intermediate: 264,
		rx: 228
	},
	bikerg: {
		scaled: 180,
		intermediate: 140,
		rx: 110
	},
	assault: {
		scaled: 210,
		intermediate: 165,
		rx: 135
	}
};
var CAL_PACE = {
	run: {
		scaled: 5,
		intermediate: 3.6,
		rx: 2.8
	},
	rowerg: {
		scaled: 3.8,
		intermediate: 2.8,
		rx: 2.1
	},
	skierg: {
		scaled: 4,
		intermediate: 3,
		rx: 2.3
	},
	bikerg: {
		scaled: 3.4,
		intermediate: 2.5,
		rx: 1.8
	},
	assault: {
		scaled: 4.2,
		intermediate: 3,
		rx: 2.2
	}
};
var REP_SEC = {
	scaled: (def) => def.pacing.max,
	intermediate: (def) => (def.pacing.min + def.pacing.max) / 2,
	rx: (def) => (def.sprint.min + def.sprint.max) / 2
};
var METER_SEC = {
	scaled: (def) => workRange(def, "pacing", "meters").max,
	intermediate: (def) => {
		const range = workRange(def, "pacing", "meters");
		return (range.min + range.max) / 2;
	},
	rx: (def) => {
		const range = workRange(def, "sprint", "meters");
		return (range.min + range.max) / 2;
	}
};
var WOD_TYPES = /* @__PURE__ */ new Set([
	"for_time",
	"amrap",
	"emom"
]);
function estimateCatalog(input) {
	const blocks = expandBlocks(input).map((block) => block.map(buildPiece));
	const confidence = confidenceOf(blocks.flat());
	const note = catalogNote(confidence);
	if (input.type === "amrap") {
		const cap = input.timeCapSec ?? 720;
		const block = blocks[0] ?? [];
		return {
			source: "catalog",
			confidence,
			note,
			scaled: amrapMark(block, cap, "scaled"),
			intermediate: amrapMark(block, cap, "intermediate"),
			rx: amrapMark(block, cap, "rx")
		};
	}
	if (input.type === "emom") {
		const minutes = Math.max(1, Math.round((input.timeCapSec ?? 60) / 60));
		const block = blocks[0] ?? [];
		return {
			source: "catalog",
			confidence,
			note,
			scaled: emomMark(block, minutes, "scaled"),
			intermediate: emomMark(block, minutes, "intermediate"),
			rx: emomMark(block, minutes, "rx")
		};
	}
	return {
		source: "catalog",
		confidence,
		note,
		scaled: forTimeMark(blocks, "scaled"),
		intermediate: forTimeMark(blocks, "intermediate"),
		rx: forTimeMark(blocks, "rx")
	};
}
function acceptGeminiTargets(type, raw, catalog, exerciseReps) {
	if (!raw || typeof raw !== "object") return null;
	const body = raw;
	const scaled = markFrom(type, body.scaled);
	const intermediate = markFrom(type, body.intermediate);
	const rx = markFrom(type, body.rx);
	if (!scaled || !intermediate || !rx) return null;
	const perRound = type === "amrap" ? repsPerRound(exerciseReps) : null;
	const marks = [
		scaled,
		intermediate,
		rx
	];
	if (!inOrder(type, marks, perRound)) return null;
	if (marks.some((mark, index) => !nearCatalog(type, mark, [
		catalog.scaled,
		catalog.intermediate,
		catalog.rx
	][index], perRound))) return null;
	return {
		source: "gemini",
		confidence: body.confidence === "low" || body.confidence === "medium" || body.confidence === "high" ? body.confidence : catalog.confidence,
		note: cleanNote(body.note, "Ritmos ajustados según la carga del WOD."),
		scaled,
		intermediate,
		rx
	};
}
function parseLevelInput(value) {
	if (!value || typeof value !== "object") return null;
	const body = value;
	if (typeof body.type !== "string" || !WOD_TYPES.has(body.type)) return null;
	const type = body.type;
	const rounds = typeof body.rounds === "number" && Number.isInteger(body.rounds) ? body.rounds : 1;
	if (rounds < 1 || rounds > 30) return null;
	let timeCapSec = null;
	if (body.timeCapSec != null) {
		if (typeof body.timeCapSec !== "number" || !Number.isInteger(body.timeCapSec)) return null;
		if (body.timeCapSec < 60 || body.timeCapSec > 10800) return null;
		timeCapSec = body.timeCapSec;
	}
	if ((type === "amrap" || type === "emom") && timeCapSec == null) return null;
	if (!Array.isArray(body.exercises) || body.exercises.length < 1 || body.exercises.length > 40) return null;
	const exercises = [];
	for (const item of body.exercises) {
		if (!item || typeof item !== "object") return null;
		const row = item;
		if (typeof row.name !== "string" || typeof row.reps !== "string") return null;
		const name = row.name.trim();
		const reps = row.reps.trim();
		if (!name || !reps || name.length > 80 || reps.length > 24) return null;
		let round = 1;
		if (row.round != null) {
			if (typeof row.round !== "number" || !Number.isInteger(row.round) || row.round < 1 || row.round > 30) return null;
			round = row.round;
		}
		let weightKg = null;
		if (row.weightKg != null) {
			if (typeof row.weightKg !== "number" || !Number.isFinite(row.weightKg)) return null;
			const rounded = Math.round(row.weightKg * 10) / 10;
			if (rounded < 1 || rounded > 300) return null;
			weightKg = rounded;
		}
		exercises.push({
			name,
			reps,
			round,
			weightKg
		});
	}
	return {
		type,
		rounds,
		timeCapSec,
		exercises
	};
}
function levelMarkLabel(type, mark) {
	return formatScoreLabel(type, mark);
}
function forTimeMark(blocks, level) {
	let total = 0;
	blocks.forEach((block, index) => {
		total += blockSeconds(block, level, FATIGUE[level] ** index);
		if (index < blocks.length - 1) total += BETWEEN[level];
	});
	return {
		elapsedSec: Math.max(1, Math.round(total)),
		rounds: null,
		reps: null
	};
}
function amrapMark(block, cap, level) {
	let elapsed = 0;
	let full = 0;
	let extra = 0;
	for (let index = 0; index < 300; index += 1) {
		const fatigue = FATIGUE[level] ** index;
		const work = blockSeconds(block, level, fatigue);
		if (work <= 0) break;
		if (elapsed + work > cap) {
			extra = partialReps(block, cap - elapsed, level, fatigue);
			break;
		}
		full += 1;
		elapsed += work;
		if (elapsed + BETWEEN[level] > cap) break;
		elapsed += BETWEEN[level];
	}
	return {
		elapsedSec: null,
		rounds: full,
		reps: extra
	};
}
function emomMark(block, minutes, level) {
	const prescribed = block.reduce((sum, piece) => sum + (piece.numericReps ?? 0), 0);
	const work = blockSeconds(block, level, 1);
	const perMinute = work <= 60 ? prescribed : Math.floor(prescribed * 60 / work);
	return {
		elapsedSec: null,
		rounds: null,
		reps: Math.min(9999, perMinute * minutes)
	};
}
function blockSeconds(block, level, fatigue) {
	let total = 0;
	block.forEach((piece, index) => {
		total += piece.seconds[level] * fatigue;
		if (index < block.length - 1) total += TRANSITION[level];
	});
	return total;
}
function partialReps(block, remainder, level, fatigue) {
	let left = remainder;
	let reps = 0;
	for (let index = 0; index < block.length && left > 0; index += 1) {
		const piece = block[index];
		const sec = piece.seconds[level] * fatigue;
		const gap = index < block.length - 1 ? TRANSITION[level] : 0;
		if (sec <= 0) {
			left -= gap;
			continue;
		}
		if (left >= sec) {
			reps += piece.numericReps ?? 0;
			left -= sec + gap;
			continue;
		}
		if (piece.numericReps != null) reps += Math.floor(piece.numericReps * left / sec);
		break;
	}
	return reps;
}
function expandBlocks(input) {
	const groups = /* @__PURE__ */ new Map();
	for (const exercise of input.exercises) {
		const round = exercise.round ?? 1;
		const list = groups.get(round) ?? [];
		list.push(exercise);
		groups.set(round, list);
	}
	const ordered = [...groups.entries()].sort((a, b) => a[0] - b[0]).map((entry) => entry[1]);
	if (input.type !== "for_time" || ordered.length !== 1) return ordered.length > 0 ? ordered : [[]];
	const times = Math.min(30, Math.max(1, input.rounds));
	return Array.from({ length: times }, () => ordered[0]);
}
function buildPiece(exercise) {
	const movement = EXERCISES.find((item) => item.name.toLowerCase() === exercise.name.trim().toLowerCase()) ?? null;
	const cardio = movement ? null : CARDIO.find((item) => item.label.toLowerCase() === exercise.name.trim().toLowerCase())?.id ?? null;
	const amount = parseAmount(exercise.reps);
	const weight = exercise.weightKg ?? null;
	const seconds = {
		scaled: 1,
		intermediate: 1,
		rx: 1
	};
	let known = false;
	let numericReps = null;
	if (movement && amount.meters != null && exerciseUnits(movement).includes("meters")) {
		known = true;
		const factor = loadFactor(movement.id, weight);
		for (const level of LEVELS) seconds[level.id] = Math.max(1, Math.round(METER_SEC[level.id](movement) * amount.meters * factor));
	} else if (movement && amount.reps != null) {
		known = true;
		numericReps = amount.reps;
		const factor = loadFactor(movement.id, weight);
		for (const level of LEVELS) seconds[level.id] = Math.max(1, Math.round(REP_SEC[level.id](movement) * amount.reps * factor));
	} else if (cardio && amount.meters != null) {
		known = true;
		for (const level of LEVELS) seconds[level.id] = Math.max(1, Math.round(amount.meters / 1e3 * DISTANCE_PACE[cardio][level.id]));
	} else if (cardio && amount.calories != null) {
		known = true;
		for (const level of LEVELS) seconds[level.id] = Math.max(1, Math.round(amount.calories * CAL_PACE[cardio][level.id]));
	} else if (amount.reps != null) {
		numericReps = amount.reps;
		for (const level of LEVELS) seconds[level.id] = Math.max(1, Math.round(GENERIC_SEC[level.id] * amount.reps));
	} else if (amount.meters != null) for (const level of LEVELS) seconds[level.id] = Math.max(1, Math.round(amount.meters / 1e3 * DISTANCE_PACE.run[level.id]));
	else if (amount.calories != null) for (const level of LEVELS) seconds[level.id] = Math.max(1, Math.round(amount.calories * CAL_PACE.rowerg[level.id]));
	else {
		numericReps = 10;
		for (const level of LEVELS) seconds[level.id] = Math.max(1, Math.round(GENERIC_SEC[level.id] * 10));
	}
	return {
		known,
		expectsWeight: movement != null && Object.prototype.hasOwnProperty.call(REFERENCE_KG, movement.id),
		hasWeight: weight != null,
		numericReps,
		seconds
	};
}
function loadFactor(id, weightKg) {
	const reference = REFERENCE_KG[id];
	if (reference == null || weightKg == null) return 1;
	return Math.min(1.7, Math.max(.75, 1 + .4 * (weightKg / reference - 1)));
}
function parseAmount(reps) {
	const text = reps.trim().toLowerCase().replace(",", ".");
	const meters = /^(\d+(?:\.\d+)?)\s*m$/.exec(text);
	if (meters) return {
		reps: null,
		meters: Number(meters[1]),
		calories: null
	};
	const calories = /^(\d+(?:\.\d+)?)\s*cal$/.exec(text);
	if (calories) return {
		reps: null,
		meters: null,
		calories: Number(calories[1])
	};
	if (/^\d+$/.test(text)) return {
		reps: Number(text),
		meters: null,
		calories: null
	};
	return {
		reps: null,
		meters: null,
		calories: null
	};
}
function confidenceOf(pieces) {
	if (pieces.length === 0 || pieces.some((piece) => !piece.known)) return "low";
	if (pieces.some((piece) => piece.expectsWeight && !piece.hasWeight)) return "medium";
	return "high";
}
function catalogNote(confidence) {
	if (confidence === "low") return "Algún movimiento no está en el catálogo; el ritmo es aproximado.";
	if (confidence === "medium") return "Ritmos del simulador. Falta peso en algún movimiento de carga.";
	return "Ritmos del simulador, con más descanso en escalado y menos en RX.";
}
function markFrom(type, value) {
	if (!value || typeof value !== "object") return null;
	const row = value;
	if (type === "for_time") {
		const elapsedSec = asInt(row.elapsedSec, 1, 21600);
		if (elapsedSec == null) return null;
		return {
			elapsedSec,
			rounds: null,
			reps: null
		};
	}
	if (type === "amrap") {
		const rounds = asInt(row.rounds, 0, 999);
		const reps = asInt(row.reps, 0, 9999);
		if (rounds == null || reps == null || rounds === 0 && reps === 0) return null;
		return {
			elapsedSec: null,
			rounds,
			reps
		};
	}
	const reps = asInt(row.reps, 0, 9999);
	if (reps == null) return null;
	return {
		elapsedSec: null,
		rounds: null,
		reps
	};
}
function asInt(value, min, max) {
	if (typeof value !== "number" || !Number.isInteger(value) || value < min || value > max) return null;
	return value;
}
function inOrder(type, marks, perRound) {
	const values = marks.map((mark) => compareValue(type, mark, perRound));
	if (values.some((value) => !Number.isFinite(value))) return false;
	if (type === "for_time") return values[0] >= values[1] && values[1] >= values[2];
	return values[0] <= values[1] && values[1] <= values[2];
}
function nearCatalog(type, mark, catalog, perRound) {
	const got = compareValue(type, mark, perRound);
	const base = compareValue(type, catalog, perRound);
	if (!Number.isFinite(got) || !Number.isFinite(base) || got <= 0 || base <= 0) return false;
	const ratio = got / base;
	return ratio >= .35 && ratio <= 3;
}
function cleanNote(value, fallback) {
	if (typeof value !== "string") return fallback;
	const note = value.replace(/\s+/g, " ").trim();
	if (!note) return fallback;
	return note.slice(0, 180);
}
//#endregion
//#region src/levelApi.ts
var GEMINI_URL = "https://generativelanguage.googleapis.com/v1beta/models";
var SCHEMA = {
	type: "OBJECT",
	properties: {
		scaled: {
			type: "OBJECT",
			properties: markSchema()
		},
		intermediate: {
			type: "OBJECT",
			properties: markSchema()
		},
		rx: {
			type: "OBJECT",
			properties: markSchema()
		},
		confidence: {
			type: "STRING",
			enum: [
				"low",
				"medium",
				"high"
			]
		},
		note: { type: "STRING" }
	},
	required: [
		"scaled",
		"intermediate",
		"rx",
		"confidence",
		"note"
	]
};
async function handleLevelRequest(request) {
	if (request.method !== "POST") return json({ error: "Método no permitido." }, 405);
	const unauthorized = await requireUser(request);
	if (unauthorized) return unauthorized;
	let body;
	try {
		body = await request.json();
	} catch {
		return json({ error: "El WOD no es válido." }, 400);
	}
	const input = parseLevelInput(body);
	if (!input) return json({ error: "El WOD no es válido." }, 400);
	const catalog = estimateCatalog(input);
	const apiKey = readEnv("GEMINI_API_KEY");
	if (!apiKey) return json(fallback(catalog, "Sin clave de Gemini en el servidor. Ritmos del simulador."));
	try {
		return json(await askGemini(input, catalog, apiKey));
	} catch (error) {
		return json(fallback(catalog, error instanceof Error ? error.message : "Gemini no respondió."));
	}
}
async function askGemini(input, catalog, apiKey) {
	const model = readEnv("GEMINI_MODEL") ?? "gemini-3.5-flash-lite";
	const response = await fetch(`${GEMINI_URL}/${model}:generateContent`, {
		method: "POST",
		headers: {
			"Content-Type": "application/json",
			"x-goog-api-key": apiKey
		},
		body: JSON.stringify({
			systemInstruction: { parts: [{ text: "Estimas ritmos de CrossFit sobre la prescripción escrita. Respondes solo JSON. No cambias movimientos ni kilos." }] },
			contents: [{
				role: "user",
				parts: [{ text: promptFor(input, catalog) }]
			}],
			generationConfig: {
				temperature: .2,
				maxOutputTokens: 500,
				responseMimeType: "application/json",
				responseSchema: SCHEMA
			}
		}),
		signal: AbortSignal.timeout(2e4)
	});
	if (!response.ok) throw new Error(`Gemini respondió ${response.status}. Ritmos del simulador.`);
	const text = (await response.json()).candidates?.[0]?.content?.parts?.map((part) => part.text ?? "").join("") ?? "";
	let raw;
	try {
		raw = JSON.parse(stripFence(text));
	} catch {
		throw new Error("Gemini no devolvió JSON. Ritmos del simulador.");
	}
	const accepted = acceptGeminiTargets(input.type, raw, catalog, input.exercises.map((exercise) => exercise.reps));
	if (!accepted) throw new Error("Gemini devolvió ritmos fuera de rango. Ritmos del simulador.");
	return accepted;
}
function promptFor(input, catalog) {
	const lines = input.exercises.map((exercise) => {
		const weight = exercise.weightKg == null ? "" : `, ${exercise.weightKg} kg`;
		return `- ${exercise.round && exercise.round > 1 ? `ronda ${exercise.round}: ` : ""}${exercise.reps} ${exercise.name}${weight}`;
	});
	const cap = input.timeCapSec == null ? "sin cap" : `${Math.round(input.timeCapSec / 60)} min`;
	return [
		"Estima tres ritmos para este mismo WOD. Escalado parte series y descansa. Intermedio es un atleta habitual de box. RX mueve bien esa carga, sin ser tiempo de Games.",
		"For time: elapsedSec en segundos; un tiempo mayor es más lento. Escalado >= intermedio >= RX.",
		"AMRAP: rounds y reps extra dentro del cap. Más trabajo es mejor: escalado <= intermedio <= RX.",
		"EMOM: reps totales. Más reps es mejor: escalado <= intermedio <= RX.",
		"Ajusta por los kilos. Puedes corregir la referencia, sin alejarte de un rango razonable.",
		"note: una frase en español, máximo 140 caracteres.",
		"",
		`Tipo: ${input.type}`,
		`Rondas del bloque: ${input.rounds}`,
		`Tiempo: ${cap}`,
		"Movimientos:",
		...lines,
		"",
		`Referencia del simulador: escalado ${levelMarkLabel(input.type, catalog.scaled)}, intermedio ${levelMarkLabel(input.type, catalog.intermediate)}, RX ${levelMarkLabel(input.type, catalog.rx)}.`
	].join("\n");
}
async function requireUser(request) {
	const header = request.headers.get("authorization") ?? "";
	const token = /^Bearer\s+(\S+)$/i.exec(header)?.[1];
	if (!token) return json({ error: "La sesión ha caducado. Vuelve a entrar." }, 401);
	const url = readEnv("VITE_SUPABASE_URL") ?? readEnv("SUPABASE_URL");
	const anon = readEnv("VITE_SUPABASE_ANON_KEY") ?? readEnv("SUPABASE_ANON_KEY");
	if (!url || !anon) return json({ error: "Falta la configuración de Supabase en el servidor." }, 500);
	if (!(await fetch(`${url.replace(/\/$/, "")}/auth/v1/user`, { headers: {
		Authorization: `Bearer ${token}`,
		apikey: anon
	} })).ok) return json({ error: "La sesión ha caducado. Vuelve a entrar." }, 401);
	return null;
}
function fallback(catalog, note) {
	return {
		...catalog,
		source: "catalog",
		note
	};
}
function markSchema() {
	return {
		elapsedSec: { type: "INTEGER" },
		rounds: { type: "INTEGER" },
		reps: { type: "INTEGER" }
	};
}
function stripFence(text) {
	const trimmed = text.trim();
	const fenced = /^```(?:json)?\s*([\s\S]*?)\s*```$/.exec(trimmed);
	return fenced ? fenced[1] : trimmed;
}
function readEnv(name) {
	const value = (globalThis.process?.env)?.[name]?.trim();
	return value ? value : void 0;
}
function json(body, status = 200) {
	return Response.json(body, { status });
}
//#endregion
//#region server/wod-levels.ts
function POST(request) {
	return handle(request);
}
var wod_levels_default = { async fetch(request) {
	return handle(request);
} };
async function handle(request) {
	try {
		return await handleLevelRequest(request);
	} catch (error) {
		const message = error instanceof Error ? error.message : "No se pudieron calcular los niveles.";
		return Response.json({ error: message }, { status: 500 });
	}
}
//#endregion
export { POST, wod_levels_default as default };
